# Rider Settings
RIDER_WEIGHT: 76.4    # My scales said 76.9, BR scales said 75.9, from Total Weight plot it went from 76.1 to 76.5kg with 76.4kg most frequent

# Bike settings
BIKE_WEIGHT: 11.1     #  bike without rod+discs
ROD_DISC_WEIGHT: 0.25 # Rod with 2x T-Clamp = 183.1g, 100mm discs with T-Clamp = 60.5g (Total 244g)  40mm discs with T-Clamp = 38.5g

CRR: 0.0025           # BR setting (see summary.csv files)
BIKE_DTL: 2.0         # Anna now using 2% (see summary.csv files)! 

# Wheel settings usually refer to the front wheel where the speed sensor is positioned 
WHEEL_CIRC_ACTUAL: 2092  # Cadex front 2092 (Giant front 2109)
WHEEL_CIRC_BR_SETTING: 2092 
REAR_WHEEL_CIRC: 2092   # Cadex rear 2092 (Giant rear 2111) - needed for determining speeds from cadence and crank angle delta
CHAINRING: 56.0         # Cadex 56 (Giant 53)
SPROCKET: 15            # from Cadence vs Ground Speed (could change gear! see code under "Add MORE FIELDS" where sprocket can be calculated)

# Height settings
COM_HEIGHT: 1.1         # using saddle height for Centre of Mass for both rider and bike (saddle was actually 1.02)
COM_RIDER_HEIGHT: 1.2   # higher than COM_HEIGHT as bike mass is excluded so all weight in body and legs. 
COP_HEIGHT: 1.2         # Centre of Pressure (centre of Frontal Area) - will be slightly higher than CoM as FA of bike is much smaller for its mass (displaced more lengthwise)
COP_RIDER_HEIGHT: 1.25  # keeping this close to COP_HEIGHT because FA of bike is small and addition of rod and discs lower than saddle will offset this 
PITOT_HEIGHT: 0.72      # Height of Pitot tube where air speed is measured (720mm for Cadex, 760mm for Giant)

# Temp Sensor used
TEMP_SENSOR_RHO: temp103T    # temp103T (HB Inclinometer) field used by BR for calculating Air Density (instead of usual Temp_C from Aerohead)

